image: continuumio/miniconda3

pages:
 script:
 - apt-get update
 - apt-get -y install build-essential
 - conda update -n base conda
 - conda env create --name tangogql python=3.6 --file=environment.yml
 - source activate tangogql
 - git clone https://gitlab.com/MaxIV/python3-taurus-core
 - cd python3-taurus-core && python setup.py install
 - pip install sphinx
 - pip install sphinx_rtd_theme
 - cd ../docs
 - make html
 - mv build/html/ ../public/
 artifacts:
   paths:
   - public
 only:
 - master
